appName = "chat_room"
debug = true

[service]
port = "9999"

[mysql]
# host = "219.223.251.93"
host = "127.0.0.1"
name = "miniecs"
password = "123456"
port = 3306
tablePrefix = ""
user = "root"

[log]
level = "trace"
path = "logs/chat.log"

[imageStorage]
filePath = "/home/fangaoyang/work"

[nodeInfo]
ip = "219.223.251.93"
port = 16509
vncbin = "/home/fangaoyang/noVNC-1.3.0/utils/novnc_proxy"
