appName = "chat_room"

[service]
port = "9999"

[mysql]
host = "127.0.0.1"
name = "miniecs"
password = "000448664"
port = 3306
tablePrefix = ""
user = "root"

[log]
level = "trace"
path = "logs/chat.log"

[imageStorage]
filePath = "/var/ecs"

[nodeInfo]
ip = "10.249.46.250"
port = 16509